In [0]:
import numpy as np

##performance difference b/w lists and arrays

In [0]:
a_array = np.arange(1000000)
a_list = list(range(1000000))

In [5]:
%time for _ in range(10) : a_array2 = a_array * 2

CPU times: user 19.3 ms, sys: 10.1 ms, total: 29.4 ms
Wall time: 31.6 ms


In [7]:
%time for _ in range(10) : a_list2 = [x * 2 for x in a_list]
  

CPU times: user 606 ms, sys: 172 ms, total: 778 ms
Wall time: 779 ms


##ndarray : N - Dimensional array

In [9]:
#random data generation
data = np.random.randn(3,2) #(rows, columns)
data

array([[-0.00607308,  0.95407802],
       [ 0.43034338, -0.09799268],
       [ 0.10284029,  0.74283819]])

In [12]:
#multiplication
data * 100 #multiplies each member of array with 100

array([[-0.6073084 , 95.40780163],
       [43.0343375 , -9.79926809],
       [10.28402878, 74.28381903]])

In [13]:
#addition
data + data #position wise

array([[-0.01214617,  1.90815603],
       [ 0.86068675, -0.19598536],
       [ 0.20568058,  1.48567638]])

In [15]:
#get shape
data.shape

(3, 2)

In [16]:
#get dtype
data.dtype

dtype('float64')

##creating nd-arrays

In [17]:
data1 = [1,2,3,4]
b_array = np.array(data1, dtype = np.int8)
b_array

array([1, 2, 3, 4], dtype=int8)

In [18]:
data1 = [[1,2,3],[6,7,8],[9,10,11]]
c_array = np.array(data1, dtype = np.int8)
c_array

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int8)

In [19]:
#get dimensions
c_array.ndim

2

In [21]:
#np.zeros
d_array = np.zeros(10)
d_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
#np.empty returns uninitialized garbage values
c_array = np.empty((3, 2, 1)) #(rows,cols,# of members)
c_array

array([[[0.01214617],
        [1.90815603]],

       [[0.86068675],
        [0.19598536]],

       [[0.20568058],
        [1.48567638]]])

In [33]:
#np.arange 
c_array = np.arange(1,15,2) #(start,stop,step)
c_array

array([ 1,  3,  5,  7,  9, 11, 13])

In [37]:
#np.ones
c_array = np.ones((2,3)) #(shape(rows,cols),dtype,order)
c_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
#np.ones_like copies shape and type
d_array = np.ones_like(c_array)
d_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
#np.full_like copies shape and type
b_array = np.array([[1,2,3],[4,5,6]],dtype=np.int8)
d_array = np.full_like(b_array, 9) #(array whose shape and type is to be copied, fill value)
d_array

array([[9, 9, 9],
       [9, 9, 9]], dtype=int8)

In [47]:
#np.full 
d_array = np.full((2,3),6) #((shape),fill val)
d_array

array([[6, 6, 6],
       [6, 6, 6]])

In [50]:
#np.eye
d_array = np.eye(5,4) #(row,col)
d_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [56]:
#np.identity
d_array = np.identity(3, dtype = np.int8)
d_array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [57]:
#np.asarray converts input into array
c = [[1,2,3],[2,7,8]]
d_array = np.asarray(c)
d_array

array([[1, 2, 3],
       [2, 7, 8]])

In [58]:
#shows dtype
d_array.dtype

dtype('int64')

In [59]:
#explicitly changing dtype array.astype
d_array = d_array.astype(np.int8)
d_array.dtype

dtype('int8')

In [61]:
#string to int/float conversion
d_array = np.array(['1.25','6.7','5.3'], dtype = np.string_ )
d_array = d_array.astype(np.float)
d_array

array([1.25, 6.7 , 5.3 ])

In [64]:
#boolean operations
d_array = np.array([1,2,3,4])
c_array = np.array([3,1,5,8])
d_array < c_array

array([ True, False,  True,  True])

##Basic Indexing and Slicing

##Transposing arrays and swapping axes

In [66]:
#Transposing array.T
d_array = np.arange(12).reshape(6,2)
d_array.T

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [72]:
#Matrix Product np.dot and @ operator
d_array = np.arange(15).reshape(5,3)
c_array = np.arange(15).reshape(3,5)
print(np.dot(c_array, d_array))
print(c_array @ d_array)

[[ 90 100 110]
 [240 275 310]
 [390 450 510]]
[[ 90 100 110]
 [240 275 310]
 [390 450 510]]


In [71]:
#ravel (changes tensor to 1D)
d_array = np.arange(12).reshape(3,4)
np.ravel(d_array)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])