In [0]:
import numpy as np

###indexing & slicing

In [0]:
arr3 = np.arange(1,37).reshape(6,6)
arr3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [0]:
arr3[2:3:,0:]      #[row, col]

array([[13, 14, 15, 16, 17, 18]])

In [0]:
arr3[2:4,3:5]      #[row, col]

array([[16, 17],
       [22, 23]])

In [0]:
arr3[4:5,:]        # : , 0 : , nothing (selects all) arr3[4], arr3[4,0:], arr3[4,:]

array([[25, 26, 27, 28, 29, 30]])

In [0]:
arr3[1:5,]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [0]:
arr3[2:4,5]

array([18, 24])

In [0]:
arr3[2:5,5:]

array([[18],
       [24],
       [30]])

In [0]:
arr3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [0]:
arr3[0:,0::2]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [0]:
arr3[0:,::-2]

array([[ 6,  4,  2],
       [12, 10,  8],
       [18, 16, 14],
       [24, 22, 20],
       [30, 28, 26],
       [36, 34, 32]])

In [0]:
arr3[::2,:]

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18],
       [25, 26, 27, 28, 29, 30]])

###boolean indexing 

In [0]:
names = np.array(['roma','lyma','sera','susu','leej','lyma', 'leej'])
data = np.random.randn(7,4)
print(names)
print(data)

['roma' 'lyma' 'sera' 'susu' 'leej' 'lyma' 'leej']
[[ 1.40500325 -2.25073847  1.70505324 -0.03463434]
 [-1.45272535 -0.40570084 -0.09009913 -0.26355054]
 [ 1.27845805 -1.36336452 -0.14709344 -0.21374081]
 [ 1.38034108 -1.65049728 -0.4433567  -0.0409417 ]
 [ 1.18827911  0.35307082  0.63250205 -0.6600096 ]
 [-1.20617486 -3.67583432  0.20262845  0.21004343]
 [ 0.36577136 -1.02514872  0.69842739 -0.11017165]]


In [0]:
bol = np.array([False, True, False, True, False, False, False], dtype = 'bool')
data[bol] #true will show up, false will not

array([[ 0.27109282, -2.36146514, -0.31760727,  0.62416178],
       [-0.03020178,  2.03947358,  1.90643982, -0.55478396]])

In [0]:
names != 'lyma'            #to get boolean positions

array([ True, False,  True,  True,  True, False])

In [0]:
data > 1                   #to get boolean positions

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [False, False, False, False]])

In [0]:
data[False,  True, False, False, False,  True]

array([], shape=(0, 7, 4), dtype=float64)

In [0]:
data[data > 1]               #to get exact values

array([1.27288451, 1.45233595, 1.80865839])

In [0]:
names[names == 'lyma']       #to get exact values

array(['lyma'], dtype='<U4')

In [0]:
condition = names!= 'lyma'
data[~condition]               #nagation

array([[-1.45272535, -0.40570084, -0.09009913, -0.26355054],
       [-1.20617486, -3.67583432,  0.20262845,  0.21004343]])

In [0]:
#condition = names!= 'lyma'
print(condition)
data = np.arange(28).reshape(7,4)
print(data)
data[condition,1:3]                #[condition = row, col] slicing

[ True False  True  True  True False  True]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


array([[ 1,  2],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [25, 26]])

In [0]:
data[condition,1:4]       #[condition = row, col] slicing

array([[ 1,  2,  3],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19],
       [25, 26, 27]])

###Multiple conditions in boolean indexing
& for and
| for or

In [0]:
cond = (names == 'lyma') | (names == 'roma')
data[cond]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [20, 21, 22, 23]])

###Fancy indexing

In [0]:
arr = np.empty((8,4))
for i in range(8):
  arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [0]:
arr[[4,0,2]]    #desired rows 

array([[4., 4., 4., 4.],
       [0., 0., 0., 0.],
       [2., 2., 2., 2.]])

In [0]:
arr[[2,0,1],[2,3,1]]      #ordered pairs (2,2),(0,3),(1,1)


array([2., 0., 1.])

In [0]:
arr[[2,3,5,7],[0,3,2,1]]
#(2,0) (3,3) (5,2) (7,1)

array([2., 3., 5., 7.])

In [0]:
arr[[1,5,7,4]][:,[0,3,1,2]]
#1[0,3,1,2],5[0,3,1,2],7[0,3,1,2],4[0,3,1,2]
#(1,0)(1,3)(1,1)(1,2),(5,0)(5,3)(5,1)(5,2),(7,0)(7,3)(7,1)(7,2),(4,0)(4,3)(4,1)(4,2)

array([[1., 1., 1., 1.],
       [5., 5., 5., 5.],
       [7., 7., 7., 7.],
       [4., 4., 4., 4.]])

In [0]:
arr2 = np.arange(32).reshape(8,4)
print(arr2)
arr2[[1,5,7,4]][:,[0,3,1,2]]
#1[0,3,1,2],5[0,3,1,2],7[0,3,1,2],4[0,3,1,2]
#(1,0)(1,3)(1,1)(1,2),(5,0)(5,3)(5,1)(5,2),(7,0)(7,3)(7,1)(7,2),(4,0)(4,3)(4,1)(4,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [16, 19, 17, 18]])

###Transpose

In [0]:
#way 1
arr.T

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [0]:
#way 2
arr.transpose()

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

###maximum, min, mean, standard deviation

###Bol funcs

In [0]:
bools = np.array([False, False, True, True])

In [0]:
bools.any() #returns true if any val is true

True

In [0]:
bools.all() #returns true if all vals are true

False



###Sort, Set, Unique


In [0]:
arr3 = np.array([7,8,5,2,1,4,5,6,6,5,4,3,1,4])
set(arr3)         #returns unique vals

{1, 2, 3, 4, 5, 6, 7, 8}

In [0]:
arr3.sort()
arr3

array([1, 1, 2, 3, 4, 4, 4, 5, 5, 5, 6, 6, 7, 8])

In [0]:
np.unique(arr3)

array([1, 2, 3, 4, 5, 6, 7, 8])

#File Input & Output with arrays

In [0]:
arr = np.arange(20)
brr = np.arange(30)
np.save('some_arr', arr)     #to save
np.load('some_arr.npy')      #to load
#more than one files
np.savez('array_archive.npz', a =arr, b=brr)
np.load('array_archive.npz')
arch['b']                    #show b

##Linear Algebra
###inverse and qr (decomposition)

In [0]:
from numpy.linalg import inv, qr

In [0]:
x = np.random.randn(5,5)
mat = x.T.dot(x)
inv(mat)

array([[ 93.35833489, -65.99646429, 132.46731334, -21.22628607,
        -46.58928547],
       [-65.99646429,  48.54397544, -95.50120844,  16.25398124,
         33.17462111],
       [132.46731334, -95.50120844, 190.68594011, -31.48443604,
        -66.30177332],
       [-21.22628607,  16.25398124, -31.48443604,   6.12622858,
         10.62462942],
       [-46.58928547,  33.17462111, -66.30177332,  10.62462942,
         23.41827973]])

In [0]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  9.08120766e-16, -1.77983298e-14,
         4.90918553e-15,  3.55681113e-14],
       [ 4.77012419e-14,  1.00000000e+00,  1.02083916e-14,
        -4.00792522e-15, -1.13294019e-14],
       [ 2.29539187e-14,  9.36811719e-15,  1.00000000e+00,
         4.14338566e-15, -1.04435634e-14],
       [ 1.51010623e-14,  5.03703500e-15,  1.55682052e-14,
         1.00000000e+00, -1.69205806e-14],
       [ 2.84555315e-14,  8.10113318e-16,  2.60201578e-14,
         5.49511688e-15,  1.00000000e+00]])

Diagonal, Tres 