In [0]:
import numpy as np

#Advanced NumPy
##Reshaping arrays
##Concatenating & Splitting Arrays
by default concatenation occurs on axis 0 <br>
as the number of rows are increased <br>
do not get confused with the  column length<br> 
add the matrices vertically, it means stack them in x asix <br>
add the matrices horizontally, it means stack them in y axis<br>
###Note : 0 for vertical , 1 for horizontal (opposite rule) 
##Stacking

In [0]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
brr = np.array([[9,10,11,12],[45,65,43,32]])
np.concatenate([arr,brr])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [45, 65, 43, 32]])

In [0]:
np.concatenate([arr,brr],axis = 0)          #vertical

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [45, 65, 43, 32]])

In [0]:
np.concatenate([arr,brr], axis = 1)         #horizontal

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 45, 65, 43, 32]])

###vstack and hstack

In [0]:
np.vstack((arr, brr))              #axis 0 rows increase

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [45, 65, 43, 32]])

In [0]:
np.hstack((arr, brr))              #axis 1 columns increase

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 45, 65, 43, 32]])

###split 
slices apart an array into multiple arrays along an axis

In [0]:
first_arr , second_arr , third_arr = np.split(arr, [1, 3])

In [0]:
first_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [0]:
second_arr

array([[5, 6, 7, 8]])

In [0]:
third_arr

array([], shape=(0, 4), dtype=int64)

In [4]:
arr = np.arange(36).reshape(6,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

###vsplit
cut horizontal

In [0]:
first, second, third = np.vsplit(arr, 3)      #horizontal, row wise split

In [0]:
first

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [0]:
second

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [0]:
third

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

###hsplit
cut vertical

In [0]:
first, second, third = np.hsplit(arr, 3)

In [0]:
first

array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19],
       [24, 25],
       [30, 31]])

In [0]:
second

array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21],
       [26, 27],
       [32, 33]])

In [0]:
third

array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23],
       [28, 29],
       [34, 35]])

##Repeat & tile

In [0]:
arr 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [0]:
np.tile(arr, 2)           #adds the same matrice on 0 axis

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 30, 31, 32, 33, 34, 35]])

In [11]:
c = np.arange(3).reshape(1,3)
print(c)
print(np.tile(c, 2))                #horizontal stacking

[[0 1 2]]
[[0 1 2 0 1 2]]
