In [0]:
import numpy as np

###How to stack two arrays vertically?

In [0]:
a = np.arange(10).reshape(2, -1)
b = np.arange(10).reshape(2, -1)
np.vstack([a,b]) #shapes of both tensors must be same

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

###How to stack two arrays horizontally?

In [0]:
a = np.arange(15).reshape(3,-1)
b = np.arange(15).reshape(3,-1)
np.hstack([a,b])

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14]])

###How to generate custom sequences in numpy without hardcoding?

ValueError: ignored

###Write a NumPy program to generate five random numbers from the normal distribution.

In [0]:
a = np.random.normal(size = 5)
a

array([ 0.99858129,  0.2538784 ,  0.97452577, -0.0145633 ,  0.02365411])

###Write a NumPy program to generate six random integers between 10 and 30.

In [0]:
a = np.random.randint(low = 10, high = 30, size = 6)
a

array([11, 27, 28, 28, 20, 10])

###Write a NumPy program to create a 3x3x3 array with random values.



In [0]:
a = np.random.random((3,3,3))
a

array([[[0.0951526 , 0.951159  , 0.81940924],
        [0.44806381, 0.58633803, 0.49280417],
        [0.31213262, 0.2214576 , 0.50033758]],

       [[0.40792286, 0.1126338 , 0.16425491],
        [0.25569597, 0.64298089, 0.1699397 ],
        [0.72024671, 0.90373319, 0.29145345]],

       [[0.27842294, 0.25816907, 0.57146473],
        [0.61233832, 0.59309937, 0.77646249],
        [0.92355834, 0.60362274, 0.6467134 ]]])

###Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [0]:
a = np.random.random((5,5))
print('array : ' , a)
print("max : " , a.max())
print("min : " , a.min())

array :  [[0.00363454 0.96635994 0.42243926 0.97819564 0.8478946 ]
 [0.83496945 0.16627462 0.40189953 0.29012174 0.83232757]
 [0.58540117 0.16704693 0.81352294 0.93372839 0.61015904]
 [0.43483638 0.30390077 0.32022194 0.82156492 0.92568088]
 [0.38350848 0.20731039 0.19750667 0.64932083 0.18328084]]
max :  0.9781956406055151
min :  0.0036345429341582136


###Create an array of shape (2, 3, 4) of zeros.

In [4]:
a = np.zeros((2,3,4))
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

###Create an array of shape (2, 3, 4) of ones.

In [5]:
a = np.ones((2, 3, 4))
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

###Create an array with values 0 to 99 using the "np.arange" function.

In [7]:
a = np.arange(0, 99)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

###Create an array from the list [2, 3.2, 5.5, -6.4, -2.2, 2.4] and assign it to the variable "a".

In [11]:
b = [2, 3.2, 5.5, -6.4, -2.2, 2.4]
a = np.array(b)
a

array([ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4])

###Do you know what a[1] will equal? Print it to see 
3.2

In [12]:
a[1]

3.2

###Try printing a[1:4] to see what that equals
3.2, 5.5, -6.4

In [13]:
a[1:4]

array([ 3.2,  5.5, -6.4])

###Create a 2-D array from the following list and assign it to the variable "a": [[2, 3.2, 5.5, -6.4, -2.2, 2.4], [1, 22, 4, 0.1, 5.3, -9], [3, 1, 2.1, 21, 1.1, -2]]

In [16]:
a = np.array([[2, 3.2, 5.5, -6.4, -2.2, 2.4], [1, 22, 4, 0.1, 5.3, -9], [3, 1, 2.1, 21, 1.1, -2]])
a

array([[ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

###Can you guess what the following slices are equal to? Print them to check your understanding. a[:, 3] a[1:4, 0:4] a[1:, 2]
a[:,3] = [-6.4, 0.1, 21.] <br>
a[1:4, 0:4] = [[ 1. , 22. ,  4. ,  0.1],
              [ 3. ,  1. ,  2.1, 21. ]] <br>
a[1:,2] = [4., 2.1]

In [17]:
a[:,3]

array([-6.4,  0.1, 21. ])

In [18]:
a[1:4, 0:4]

array([[ 1. , 22. ,  4. ,  0.1],
       [ 3. ,  1. ,  2.1, 21. ]])

In [20]:
a[1:,2]

array([4. , 2.1])

###Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it to the variable "arr".Print the shape of the array. Print the size of the array. Print the maximum and minimum of the array.

In [23]:
a = [x for x in range(4)]
b = [x for x in range(10,14)]
arr = np.array([a,b])
print(arr.shape)
print(arr.size)
print('maximum : ', arr.max())
print('minimum : ', arr.min())

(2, 4)
8
maximum :  13
minimum :  0


###Continue to use the array "arr" as defined above.Print the array re-shaped to (2, 2, 2).Print the array transposed.Print the array flattened to a single dimension. Print the array converted to floats.

In [29]:
print(arr)
print(arr.reshape((2,2,2)))
print(arr.transpose())
print(arr.ravel())
arr.astype(np.float)

[[ 0  1  2  3]
 [10 11 12 13]]
[[[ 0  1]
  [ 2  3]]

 [[10 11]
  [12 13]]]
[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]]
[ 0  1  2  3 10 11 12 13]


array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.]])

###Create an an array counting from 1 to 20 inclusive.

In [30]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

###The array of multiples of 3 greater than 0 and less than 30.

In [31]:
a = np.arange(0,31,3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

###The array of 8 equally spaced floats x where 0 ≤ x ≤ 1.

In [33]:
a = np.linspace(0,1,8)
a

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

###Use np.arange and reshape to create the array A = [[1 2 3 4] [5 6 7 8]]

In [34]:
a = np.arange(1, 9).reshape(2,4)
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

###Use np.array to create the array B = [1 2]

In [35]:
a = np.array([1,2])
a

array([1, 2])

###Use broadcasting to add B to A to create the final array A + B

In [42]:
b = np.array([[2,3],[4,5],[7,8]])
a, b = np.broadcast_arrays(a,b)
c = a + b
c

array([[ 3,  5],
       [ 5,  7],
       [ 8, 10]])